import React, {useEffect, useState} from 'react';
const fmt = (v, digits=2) => v == null ? '—' : Number(v).toFixed(digits);
export default function ComparisonView() {
  const [report,setReport]=useState(null), [day,setDay]=useState(''), [block,setBlock]=useState('');
  const [pins,setPins]=useState(null), [refresh,setRefresh]=useState(0), [error,setError]=useState('');
  const [busy,setBusy]=useState(true), [search,setSearch]=useState('');
  useEffect(()=>{
    const controller=new AbortController(); setBusy(true); setError('');
    const q=new URLSearchParams(); if(day)q.set('valid_date',day); if(block)q.set('block',block);
    if(pins){q.set('block_run_id',pins[0]);q.set('district_run_id',pins[1]);}
    fetch('/api/comparison?'+q,{signal:controller.signal}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.detail);return x;})
      .then(x=>{if(!controller.signal.aborted)setReport(x);})
      .catch(e=>{if(e.name!=='AbortError')setError(e.message);})
      .finally(()=>{if(!controller.signal.aborted)setBusy(false);});
    return ()=>controller.abort();
  },[day,block,pins,refresh]);
  function select(nextDay,nextBlock){setPins([report.block_source.run_id,report.district_source.run_id]);setDay(nextDay);setBlock(nextBlock);}
  const rows=report?.rows || [], stats=report?.summary;
  const [blockNames,setBlockNames]=useState([]);
  useEffect(()=>{if(report && !report.selected_block)setBlockNames(report.by_block.map(b=>b.block));},[report]);
  const max=Math.max(1,...rows.flatMap(r=>[r.block_local_mm,r.district_local_mm]));
  const shown=rows.filter(r=>(r.name+' '+r.panchayat_id).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Math.abs(b.difference_mm)-Math.abs(a.difference_mm));
  return <section className="comparison">
    <div className="comparison-heading"><div><h2>Same-day forecast comparison</h2><p>Block → village versus district → village · matched weather forecasts</p></div><button onClick={()=>{setPins(null);setDay('');setBlock('');setRefresh(x=>x+1);}}>Compare latest sources</button></div>
    {error && <p role="alert" className="warning">{error} No substitute dates or forecasts are used.</p>}
    {busy && <p role="status">Pairing villages and shared forecast dates…</p>}
    {report && !busy && !error && <>
      <div className="controls"><label>Comparison day<select value={report.valid_date} onChange={e=>select(e.target.value,block)}>{report.overlap_dates.map(d=><option key={d}>{d}</option>)}</select></label><label>Comparison block<select value={block} onChange={e=>select(report.valid_date,e.target.value)}><option value="">All paired blocks</option>{blockNames.map(b=><option key={b}>{b}</option>)}</select></label></div>
      <div className="comparison-provenance"><p><strong>Block issue: {report.block_source.issue_date}</strong><br/>Manually imported · {report.block_source.freshness}</p><p><strong>District issue: {report.district_source.issue_date}</strong><br/>{report.district_source.cache_status} · {report.district_source.freshness}</p><p><strong>{stats.count.toLocaleString()} paired villages</strong><br/>Exactly matched by village ID and date</p></div>
      <p className="warning">{report.district_issue_days_later === 0 ? 'Same issue date; exact issue times remain unknown.' : `District issue is ${report.district_issue_days_later} calendar day(s) later than the block issue. This includes a forecast-update difference.`} Agreement does not establish accuracy. Exact rainfall accumulation hours are unverified.</p>
      {report.district_source.last_retrieval_error && <p className="warning">District retrieval failed; comparing cached bulletin: {report.district_source.last_retrieval_error}</p>}
      <div className="comparison-metrics">{[['Block mean',stats.block_mean_mm],['District mean',stats.district_mean_mm],['Mean absolute difference',stats.mean_absolute_difference_mm],['Largest difference',stats.max_absolute_difference_mm]].map(([label,n])=><div key={label}><span>{label}</span><strong>{fmt(n)} <small>mm</small></strong></div>)}</div>
      <p>Each village counts equally above. Area-weighted means: block {fmt(stats.area_weighted_block_mm)} mm; district {fmt(stats.area_weighted_district_mm)} mm. {stats.above_5mm} villages differ by more than 5 mm; {stats.different_20mm_trigger} cross the app's 20 mm advisory threshold differently.</p>
      <div className="comparison-grid"><section className="notes"><h3>How closely do the paths agree?</h3><svg viewBox="0 0 480 340" role="img" aria-label="Paired rainfall scatter plot. Horizontal axis district estimate; vertical axis block estimate. Diagonal indicates agreement.">
        <line x1="55" y1="285" x2="440" y2="25" stroke="#93a9bc" strokeDasharray="6 5"/>
        <path d="M55 25 V285 H440" fill="none" stroke="#93a9bc"/>
        {[0,.25,.5,.75,1].map(q=><g key={q}><text x={55+385*q} y="306" textAnchor="middle">{fmt(max*q,1)}</text><text x="48" y={289-260*q} textAnchor="end">{fmt(max*q,1)}</text></g>)}
        {rows.map(r=><circle key={r.panchayat_id} cx={55+385*r.district_local_mm/max} cy={285-260*r.block_local_mm/max} r="3" fill={r.difference_mm>=0?'#55d8ec':'#ffbe70'} opacity=".55"><title>{r.name}: block {fmt(r.block_local_mm)}, district {fmt(r.district_local_mm)}, difference {fmt(r.difference_mm)} mm</title></circle>)}
        <text x="247" y="334" textAnchor="middle">District-derived rainfall (mm)</text><text x="14" y="160" transform="rotate(-90 14 160)" textAnchor="middle">Block-derived rainfall (mm)</text>
      </svg><p>Above the diagonal: block higher. Below: district higher. Points can overlap; this is a disagreement chart, not a skill score.</p></section>
      <section className="notes"><h3>Why the same terrain gives different values</h3><p>Both paths reuse the same village elevation and learned rainfall pattern. Each path scales that pattern to a different parent: its block or the whole district.</p><p>Local rainfall = parent forecast × village factor. A factor is the village climatology divided by its parent's area-weighted climatology. The denominator changes even though the village stays fixed.</p><p>For this selection, the signed mean difference is {fmt(stats.mean_difference_mm)} mm. A symmetric algebraic split gives {fmt(stats.mean_source_component_mm)} mm from parent source differences and {fmt(stats.mean_reference_component_mm)} mm from reference-factor differences. Components can cancel; this is not causal attribution.</p><p>The model is experimental. Different issue times, forecast lead times and source products can contribute, but their separate effects cannot be identified from these two bulletins.</p></section></div>
      <section className="notes"><h3>Across the shared forecast dates</h3><div className="comparison-table"><table><thead><tr><th>Date</th><th>Block mean</th><th>District mean</th><th>Mean |difference|</th><th>RMS difference</th><th>Max |difference|</th></tr></thead><tbody>{report.by_date.map(s=><tr key={s.valid_date}><th>{s.valid_date}</th><td>{fmt(s.block_mean_mm)}</td><td>{fmt(s.district_mean_mm)}</td><td>{fmt(s.mean_absolute_difference_mm)}</td><td>{fmt(s.root_mean_square_difference_mm)}</td><td>{fmt(s.max_absolute_difference_mm)}</td></tr>)}</tbody></table></div><p>Excluded dates: block only {report.block_only_dates.join(', ') || 'none'}; district only {report.district_only_dates.join(', ') || 'none'}. No date shifting or interpolation.</p></section>
      <section className="notes"><h3>Block comparison · {report.valid_date}</h3><div className="comparison-table"><table><thead><tr><th>Block</th><th>Villages</th><th>Block mean</th><th>District mean</th><th>Signed difference</th><th>Mean |difference|</th></tr></thead><tbody>{report.by_block.map(s=><tr key={s.block}><th>{s.block}</th><td>{s.count}</td><td>{fmt(s.block_mean_mm)}</td><td>{fmt(s.district_mean_mm)}</td><td>{fmt(s.mean_difference_mm)}</td><td>{fmt(s.mean_absolute_difference_mm)}</td></tr>)}</tbody></table></div></section>
      <section className="notes"><h3>Village detail</h3><label>Find village or ID <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Village name or code"/></label><p>Sorted by largest absolute difference. Showing {Math.min(100,shown.length)} of {shown.length} matches. Percent change uses district rainfall as denominator; zero denominators are unavailable.</p><div className="comparison-table"><table><thead><tr><th>Village / block</th><th>Block source</th><th>District source</th><th>Block local</th><th>District local</th><th>Difference</th><th>% vs district</th></tr></thead><tbody>{shown.slice(0,100).map(r=><tr key={r.panchayat_id}><th>{r.name}<small>{r.block} · {r.panchayat_id}</small></th><td>{fmt(r.block_source_mm)}</td><td>{fmt(r.district_source_mm)}</td><td>{fmt(r.block_local_mm)}</td><td>{fmt(r.district_local_mm)}</td><td>{fmt(r.difference_mm)}</td><td>{fmt(r.percent_vs_district,1)}</td></tr>)}</tbody></table></div></section>
      <section className="notes"><h3>All-weather comparison · {report.valid_date}</h3><div className="comparison-table"><table><thead><tr><th>Variable</th><th>Pairs</th><th>Block mean</th><th>District mean</th><th>Mean |difference|</th><th>Max |difference|</th></tr></thead><tbody>{Object.entries(report.weather_summary || {}).map(([k,s])=><tr key={k}><th>{({rainfall_mm:'Rainfall (mm)',temp_max_c:'Maximum temperature (°C)',temp_min_c:'Minimum temperature (°C)',relative_humidity_max_pct:'Maximum humidity (%)',relative_humidity_min_pct:'Minimum humidity (%)',wind_speed_kmph:'Wind speed (km/h)',cloud_cover_oktas:'Cloud cover (oktas)'})[k]}</th><td>{s.count}</td><td>{fmt(s.block_mean)}</td><td>{fmt(s.district_mean)}</td><td>{fmt(s.mean_absolute_difference)}</td><td>{fmt(s.max_absolute_difference)}</td></tr>)}</tbody></table></div><p>Missing values are unavailable, never zero. Qualitative district cloud descriptions cannot be compared numerically with block oktas. Wind direction is unavailable in the district source.</p></section>
      <section className="notes"><h3>What this comparison cannot establish</h3><p>These are village polygons, without a verified gram-panchayat crosswalk. Temperature, humidity and wind summaries pair numeric values when both sources supply them.</p><p>No source wins on accuracy from this comparison. Compare both against independent observations at matched locations, accumulation intervals and lead times before selecting or blending them.</p><details><summary>Snapshot provenance</summary><p className="wrap">{report.comparison_id}<br/>Block run: {report.block_source.run_id}<br/>District run: {report.district_source.run_id}<br/>Model: {report.block_source.model_version}<br/>District downloaded: {report.district_source.downloaded_at}</p><p>{report.decomposition}</p></details></section>
    </>}
  </section>;
}
